name: Staging Docs

on:
  push:
    branches:
      - 'dev'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'VuesaxAlphaBot' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Compile Vuesax Alpha
        run: pnpm build
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Build Metadata
        run: cd internal/metadata && pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build website
        run: pnpm docs:build
        env:
          DOC_ENV: staging
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Deploy staging website
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          token: ${{ secrets.VS_BOT_TOKEN }}
          branch: main
          folder: docs/.vuepress/dist
          repository-name: vuesax-alpha/staging
          git-config-name: VuesaxAlphaBot
